---
version: build-{build}
skip_non_tags: true
environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    BITS: 64
  - TARGET: i686-pc-windows-msvc
    BITS: 32
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    BITS: 32
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.16.0-${env:TARGET}.exe" -FileName "rust-stable.exe"
  - rust-stable.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - ps: $env:PATH="$env:PATH;C:\MinGW\bin"
  - rustc -V
  - cargo -V
build: off
test_script:
  # Compile and check if the binary works
  - cargo build --release
  - cargo run --release -- --help

