[package]
name = "rat"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[[bin]]
name = "rat"
path = "src/main.rs"

[dependencies]
clap = "2"
curl = "0.4"
itertools = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
toml = "0.3"
